force-app/main/default/objects/customer__c/customer__c.object-meta.xml
<CustomObject>
    <label>customer</label>
    <nameField>
        <label>customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/customer__c/fields/Tax__c.field-meta.xml
<CustomField>
    <fullName>Tax__c</fullName>
    <label>Tax</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transactions__c/Transactions__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <label>Transactions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transactions__c/fields/Ammount__c.field-meta.xml
<CustomField>
    <fullName>Ammount__c</fullName>
    <label>Ammount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TriggerExample.cls
global class TriggerExample {
    global static void calculateTax(customer__c[] cust )
    
    {
        for(customer__c c:cust)
    {
     if(c.Ammount__c > 500000)
     {
         	c.Tax__c = string.valueOf(c.Ammount__c * 0.10); 
     }   
      else
      {
       c.Tax__c = string.valueOf(c.Ammount__c * 0.50); 
      }
    
    }
}

 global static void CreateTransaction(customer__c [] cust )
{
 list<Transactions__c>TR = new  list<Transactions__c>();
     for(customer__c c:cust)
    {
      Transactions__c t = new Transactions__c(Name = c.Name,Ammount__c = c.Ammount__c); 
        TR.add(t);
  
    }

insert TR;
}
}