force-app/main/default/objects/customer__c/customer__c.object-meta.xml
<CustomObject>
    <label>customer</label>
    <nameField>
        <label>customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transactions__c/Transactions__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <label>Transactions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transactions__c/fields/Ammount__c.field-meta.xml
<CustomField>
    <fullName>Ammount__c</fullName>
    <label>Ammount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/InsertCustomerTest.cls
@istest
public class InsertCustomerTest {
static Testmethod void testcustomer()
{
    customer__c x = new customer__c();
    x.Name = 'cust1';
    x.Ammount__c = 1000;
    x.phone__c = '9502774360';
    insert x;
    
    Transactions__c t = new Transactions__c();
    t.Name = x.Name;
    t.Ammount__c = x.Ammount__c;
    t.phone__c = x.phone__c;
    insert t;
  system.assertEquals(t.Name, x.Name);
  system.assertEquals(t.Ammount__c, x.Ammount__c); 
   x.Name = 'cust11';
   x.Ammount__c = 30000;
    update x;
    
    
    
    
}
}