force-app/main/default/objects/Contact/fields/ContactRelationship__c.field-meta.xml
<CustomField>
    <fullName>ContactRelationship__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ContactRelationship</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact_Relationship__c/Contact_Relationship__c.object-meta.xml
<CustomObject>
    <label>Contact Relationship</label>
    <nameField>
        <label>Contact Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ContactMasterHandler.cls
public class ContactMasterHandler {
public void createContactRelationshipByContact(list<Contact>ListOfContacts)
{
  list<Contact_Relationship__c> cnlist = new list<Contact_Relationship__c>();
      for(Contact C :ListOfContacts)
      {
      if(C.ContactRelationship__c == true)
  {
      Contact_Relationship__c cn = new Contact_Relationship__c();
      cn.Name = C.LastName;
      cn.Contact__c = C.Id; 
      cnlist.add(cn);
  }
}
insert cnlist;
  
}
 }